# Generated by Django 3.1.7 on 2021-04-12 17:47

import autoslug.fields
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Job Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country', models.CharField(default='Egypt', max_length=500)),
                ('city', models.CharField(default='Cairo', max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('job_title', models.CharField(blank=True, default='Just Client', max_length=500, null=True)),
                ('profile_img', models.ImageField(upload_to='imgs/')),
                ('category', models.CharField(choices=[('CM', 'Craftsman'), ('Emp', 'Employer')], default='Emp', max_length=500)),
                ('rate', models.IntegerField()),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.category')),
            ],
            options={
                'db_table': 'Clients',
                'ordering': ('first_name',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', models.TextField(max_length=2000)),
                ('location', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/')),
                ('min_bid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('max_bid', models.DecimalField(decimal_places=2, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.client')),
            ],
            options={
                'db_table': 'Jobs',
                'ordering': ['job_title'],
            },
        ),
    ]
